apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nginx-demo.fullname" . }}-index
  namespace: {{ .Values.namespace }}
data:
  index.html.template: |
    <html>
    <head>
      <title>NGINX Demo</title>
    </head>
    <body>
      <h1>NGINX Load Balancer Demo</h1>
      <p>Pod hostname: ${MY_POD_NAME}</p>
    </body>
    </html>
