apiVersion: v1
kind: Service
metadata:
  name: {{ include "nginx-demo.fullname" . }}-service
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "nginx-demo.name" . }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 80

