namespace: demo

replicaCount: 5

image:
  repository: "207457247351.dkr.ecr.us-east-2.amazonaws.com/devops/nginx"
  tag: "e48b57b23fde2c506ebe9fa57637f50d3f517e9e"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: alb
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
  path: /
  pathType: Prefix

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  cpuTarget: 50

