namespace: demo

replicaCount: 5

image:
  repository: "207457247351.dkr.ecr.us-east-2.amazonaws.com/devops/nginx"
  tag: "de48578b243fa25bdd03330d9ff3a5abdf15ef9a"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: alb
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
  path: /
  pathType: Prefix

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  cpuTarget: 50

